### ISSUE TITLE
Converting continuous.dat into SpikeGLX flat binary

### ISSUE THREAD

**Issue by guidomeijer** [open-ephys/analysis-tools#105]
Hi! I'm using OpenEphys to record Neuropixel data but want to use pyKilosort for spike sorting which only accepts bin files (from SpikeGLX) as input. So I'd like to convert the OpenEphys output to SpikeGLX output. The data is in one large (~80GB) continuous.dat file. When I try to use the `loadContinuous` function to read this in I get the `File size is not consistent with a continuous file: may be corrupt` error. This function seems to expect many continuous files of a fixed size instead of a single large file. Loading in the large file anyway does not work because it tries to load in the whole file in one go resulting in a `MemoryError`. How should I proceed?

**Comment by jsiegle** [comment]
Hi Guido! Hopefully you saw Pavel's response in the Neuropixels Slack channel, but I'll add some more info here so it's archived:

- The only formatting difference between `.bin` and `.dat` files is the extension. They are both flat binary files of signed 16-bit integers. You should be able to point `pykilosort` to the `.dat` file and have it work automatically. If you're having trouble with this, let us know.

- There *is* a difference in the scaling that's applied by the recording software before writing. This doesn't matter for spike sorting, but it will be important for loading the data for further analysis. SpikeGLX writes the raw ADC values from the Neuropixels probe, so converting to microvolts requires knowledge of the gain that was used. Open Ephys scales all samples to have a "bitVolts" value of 0.195, regardless of the amplifier gain. 

- The `analysis-tools` repo is no longer being maintained. Instead, we recommend using [`open-ephys-python-tools`](https://github.com/open-ephys/open-ephys-python-tools) or [`open-ephys-matlab-tools`](https://github.com/open-ephys/open-ephys-matlab-tools), which we'll be keeping up to date. We just updated the `analysis-tools` README with this info.

**Comment by guidomeijer** [comment]
Hi Josh, thanks so much for your answer! Great that both raw data files are already flat binary, I should have known but I got thrown off by the existence of the `.continuous` files that the OpenEphys outputs in other cases. The scaling is also very good to know, thanks. There is one thing remaining: pykilosort also requires the SpikeGLX `.meta` file to run. I can probably write a conversion script that converts the OpenEphys metadata XML file into the meta data from SpikeGLX, but do you know whether such a conversion script already exists?

**Comment by jsiegle** [comment]
A notebook for generating a .meta file from an Open Ephys recording directory is available here: https://www.dropbox.com/s/72dbum80z43zkh8/meta_file_generator.ipynb?dl=0

We plan to integrate these functions into `open-ephys-python-tools` eventually, but for now you'll just have to run the notebook (editing cells where appropriate).

At the Allen Institute, we have been running pykilosort via SpikeInterface, which can seamlessly read data from both SpikeGLX and Open Ephys. I assume you're using the IBL pipeline for pre/post-processing, but I'd recommend checking out SpikeInterface when you have time.

**Comment by guidomeijer** [comment]
Thanks Josh, spikeinterface is exactly what I needed, it works great!
