### ISSUE TITLE
load_open_ephys_data_faster.m skips chunks of data

### ISSUE THREAD

**Issue by mmyros** [open-ephys/analysis-tools#19]
My example file is here: https://iu.box.com/s/68nel6xs7g73z6i732dgp4guintjsnyr

The faster function skips chunks of data over 10001 samples or more long
```
[~, ts]=load_open_ephys_data_faster('100_CH19.continuous');
db_fast=diff(ts);
db_fast(db_fast>100)
```
returns three instances:
```    
 10001
 10001
111245 
```

They are located somewhere in the middle:
```
find(db_fast>100)
ans =
     4659200
     8309760
    50656256 
length(db_fast)
ans =
   266704895
```

Wheres load_open_ephys_data.m does not:
```
[~, ts]=load_open_ephys_data('100_CH19.continuous');db=diff(ts);find(db>100)

ans =
   Empty matrix: 0-by-1
```

**Comment by aacuevas** [comment]
Keep in mind that, while the faster version returns timestamps as raw sample numbers, the normal version converts them to seconds. Thus, even if there were a skip in the data parsed by the function, it definitely wouldn't be greater than 100 seconds.

Please comment out line 457 of load_open_ephys_sata.m, the one that does the sample number to seconds conversion, and check if that discrepancy still exists.

Aarón.

**Comment by mmyros** [comment]
That fixed it. Thanks for your help! The skips are there, but the loading functions are fine. It's very strange, the events don't seem to line up with the timestamps of continuous data. 

I recorded a long session, and the response in PSTH  initially lines up quite nicely with the events and then shifts to an earlier time... The event timestamps should line up with .continuous timestamps regardless of any missing data, right? (please see attachment)
![bug](https://cloud.githubusercontent.com/assets/3022307/12134208/fc007642-b3fa-11e5-9902-de9d1bf750bc.png)
