### ISSUE TITLE
keyError when attempting to create .dat file with OpenEphys.py

### ISSUE THREAD

**Issue by ThomasAkam** [open-ephys/analysis-tools#3]
When I try to create a .dat file from a folder of data saved in Open Ephys format using the pack function of OpenEphys.py I get the following error:

    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Anaconda\lib\site-packages\OpenEphys\OpenEphys.py", line 316, in pack
    ch = data[''.join((source,'_CH',str(order[j]).replace(source+'_CH','')))]['data']
    KeyError: '100_CH100_AUX2'

Changing line 316 from:

    ch = data[''.join((source,'_CH',str(order[j]).replace(source+'_CH','')))]['data']

to:

    ch = data[order[j]]['data']

prevents this error, and the program then outputs data files that appear to be correct.

**Comment by jsiegle** [comment]
Thanks for pointing that out! I just made the change.
