### ISSUE TITLE
load_open_ephys_data_faster decreases data resolution

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/analysis-tools#30]
I noticed that load_open_ephys_data_faster.m currently outputs continuous data with lower resolution than load_open_ephys_data.m, which I don't think is intentional. Specifically, one change made in pull request #26 (line 150 in the current file) causes the data values read in from the continuous file to be stored in an int16 matlab array (which is fine so far, since they are integers). Then, when they are scaled by info.header.bitVolts in line 120, the result is automatically rounded to another int16 array. In contrast, load_open_ephys_data.m reads the data in as doubles, so they are not rounded after multiplying. In my case, the bitVolts value was about 0.2, so reading data with this function decreased the resolution by about 5 times.

Is there a good reason for writing to an int16 array in the fread function? Otherwise, that could just be reverted.

-Ethan

**Comment by mmyros** [comment]
There was an thread in groups in which people were having trouble fitting data in memory when looping over large arrays. Perhaps a better alternative would be to not scale by bitvolts until later in the analysis. Maybe we could implement an input option that would result in either scaling and double, or no scaling and int16.

**Comment by ethanbb** [comment]
OK, after reading that thread, I see the benefit of using int16's in the type of operation that Ainhoa was attempting. Your suggestion of providing a choice sounds like a reasonable solution. I think that scaling and double should be the default (since it would cover most use cases, except those involving large data operations), does that sound good?

I can go ahead and make that change and submit a pull request.

**Comment by mmyros** [comment]
Sure, thanks!
