### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by galenlynch** [open-ephys/analysis-tools#33]
What is the license of this repository?

**Comment by jsiegle** [comment]
Good question. I would favor an MIT License for all of the things I've written, but there are a number of other contributors here. We may have to take it on a case-by-case basis, rather than using one license for the whole repo. Any thoughts from others on how to handle this?

**Comment by galenlynch** [comment]
Some files, such as [load_open_ephys_data_faster.m](https://github.com/open-ephys/analysis-tools/blob/master/load_open_ephys_data_faster.m), already have a license (GPL in this example).
