### ISSUE TITLE
Julia data loader

### ISSUE THREAD

**Issue by galenlynch** [open-ephys/analysis-tools#39]
I recently put a Julia package [for loading Open Ephys .continuous data files](https://github.com/galenlynch/OpenEphysLoader.jl) on github. I want to keep it as a separate repository so that Julia's package manager can use it, but it might be useful here as well.

**Comment by jsiegle** [comment]
That's awesome! I think it's better if the Julia package lives in a separate repository. I just added a link to it in the README file, so people can find it more easily.

**Comment by galenlynch** [comment]
Thanks for adding a link to the README file. It can also read the XML metadata files, if that is of any use to people.
