### ISSUE TITLE
Timestamps out of order

### ISSUE THREAD

**Issue by wehrlab** [open-ephys/analysis-tools#40]
When using load_open_ephys_data, we have an issue of timestamps missing and being out of order. They can skip ahead, which results in losing some samples or they can skip backwards, which makes them misaligned. This happens frequently throughout recording. I'm using the latest open ephys version compiled on linux computer.

**Comment by jonnew** [comment]
Why was this issue closed?

**Comment by jvoigts** [comment]
i think this has been moved to https://github.com/open-ephys/plugin-GUI/issues/126

**Comment by mikewehr** [comment]
Indeed, #126 is the same issue. I didn't realize Iryna had recently posted about it.
