### ISSUE TITLE
Convert between formats.

### ISSUE THREAD

**Issue by holmescharles** [open-ephys/analysis-tools#71]
Is there a trivial way to convert between flat binary to the open-ephys formats? I see there is a tool to convert between open-ephys and kwik. Has this been generalized?

Thanks!

**Comment by malfatti** [comment]
I wrote a python function to [load binary files](https://gitlab.com/malfatti/SciScripts/blob/master/Python3/Deps/IO/OpenEphys.py) (see line 85), and another one to [write data to a HDF5 file](https://gitlab.com/malfatti/SciScripts/blob/master/Python3/Deps/IO/Hdf5.py) (although it will not match the .kwik architecture, see line 33). If it helps, I would be happy to open a PR to add them here :)

**Comment by holmescharles** [comment]
I appreciate that very much! But I was hoping to convert to the open-ephys format, which I don't think is trivial to handle.

At any rate, I just decided a few hours ago to stick with flat binaries. I was planning on using Spyking circus to sort spikes, but the OpenEphys data type doesn't seem to play nice.

**Comment by holmescharles** [comment]
Since I no longer need this, I'm going to close the issue. If anyone wants to re-open it, you're welcome to do so!

**Comment by matinsaba** [comment]
how did you get channel data from Binary formatted data?

**Comment by jsiegle** [comment]
See #90
