### ISSUE TITLE
Bug in OpenEphys.py loadEvents

### ISSUE THREAD

**Issue by ThomasAkam** [open-ephys/analysis-tools#8]
When I try to use loadEvents from OpenEphys.py to import event files into python I get the following error:

    File "C:\Anaconda\lib\site-packages\OpenEphys\OpenEphys.py", line 241, in loadEvents
        nodeId[index] = np.fromfile(f, np.dtype('<ui'), 1)

    TypeError: data type "<ui" not understood

Changing line 241 to:

    nodeId[index] = np.fromfile(f, np.dtype('<u1'), 1)

resolves the problem.

**Comment by jsiegle** [comment]
Good catch! I just fixed it.
