### ISSUE TITLE
recovering timestamps

### ISSUE THREAD

**Issue by shirquinn** [open-ephys/analysis-tools#98]
Hi
I was analyzing my binary recording with kilosort, and as a result my timestamps.npy file in the continuous folder got deleted :(
Is there a way to recover this file? i still have the continuous file and the structure file

**Comment by jsiegle** [comment]
The easiest way to recover the timestamps is by looking at `sync_messages.txt`, which contains the first recorded sample number for each subprocessor. Assuming there were no recording glitches, `timestamps.npy` will start with this number and then increment by 1 for each recorded sample. Let me know if that works!
