### ISSUE TITLE
OEP v0.6.2 Python KeyError: 'source_processor_sub_idx

### ISSUE THREAD

**Issue by MannyEsguerra** [open-ephys/analysis-tools#99]
We upgraded to OEP 0.6.2, and now cannot read continuous data with our Python scripts, ie opening a Session object and reading data works only for data collected with v 0.5. 

For example, 
recording_cont = sessions.recordnodes[0].recordings[index].continuous[0] throws this error:

![source_processor_error](https://user-images.githubusercontent.com/46828260/195374391-67ee9636-f17e-4bae-8069-765ed4c1431f.png)

**Comment by jsiegle** [comment]
Hi Manny – there's a new version of `open-ephys-python-tools` that works with v0.6.x: https://github.com/open-ephys/open-ephys-python-tools/tree/0.6.0

If you install from the `0.6.0` branch (instructions in the README file), everything should work again.

We will soon add this version to PyPI and make it the default branch.

**Comment by MannyEsguerra** [comment]
Thank you so much, I missed that somehow. Will it handle files from 0.5?

**Comment by jsiegle** [comment]
Yeah, the package can only handle files from one version or the other. In the future we would like to add backwards compatibility for 0.5.x.
